#server:
#  port: 12000
spring:
  zipkin:
    base-url: http://192.168.127.138:9411/
    #zipkin关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #采样器，默认为0.1，即采样10%；
#  datasource:
#    username: root
#    password: lcl19960822
#    url: jdbc:mysql://192.168.127.135:3308/gulimall_rms
#    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gulimall-repository
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.127.138
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

#mybatis-plus:
#  mapper-locations: classpath:/mapper/repository/*.xml
#  #  主键自增
#  global-config:
#    db-config:
management:
  endpoints:
    web:
      exposure:
        include: "*"
#      id-type: auto
logging:
  level:
    #远程调用打印日志
    org.springframework.cloud.openFeign: debug
    #链路追踪打印日志
    org.springframework.cloud.sleuth: debug