spring:
  datasource:
    username: root
    password: lcl19960822
    url: jdbc:mysql://192.168.127.138:3308/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  关闭thymeleaf缓存
  thymeleaf:
    cache: false
  redis:
    host: 192.168.127.138
    port: 6379
  cache:
    # use redis as cache
    type: redis
    redis:
      # set cache expiration time, unit: ms
      time-to-live: 3600000
      # add prefix for keys in the cache
#      key-prefix: CACHE_
      # enable use cache prefix
      use-key-prefix: true
      # cahce null value, prevent cache penetration
      cache-null-values: true
  session:
    store-type: redis
  zipkin:
    base-url: http://192.168.127.138:9411/
    #zipkin关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #采样器，默认为0.1，即采样10%；
mybatis-plus:
  mapper-locations: classpath:/mapper/product/*.xml
#  主键自增
  global-config:
    db-config:
      id-type: auto
#      配置全局的逻辑删除规则
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 9000
logging:
  level:
    com.lichenglin.gulimall.product: debug
    #远程调用打印日志
    org.springframework.cloud.openFeign: debug
    #链路追踪打印日志
    org.springframework.cloud.sleuth: debug
gulimall:
  thread:
    core-pool-size: 30
    max-pool-size: 200
    keep-alive-time: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true

