spring:
  datasource:
    username: root
    password: lcl19960822
    url: jdbc:mysql://192.168.127.135:3308/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/product/*.xml
#  主键自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000