spring:
  datasource:
    username: root
    password: lcl19960822
    url: jdbc:mysql://192.168.127.135:3308/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/product/*.xml
#  主键自增
  global-config:
    db-config:
      id-type: auto
#      配置全局的逻辑删除规则
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 9000
logging:
  level:
    com.lichenglin.gulimall.product: debug
