server:
  port: 20000
spring:
  zipkin:
    base-url: http://192.168.127.138:9411/
    #zipkin关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #采样器，默认为0.1，即采样10%；
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
        #微服务与控制台之间的数据传输使用该端口；
        port: 8719
  redis:
    host: 192.168.127.138
    port: 6379
  thymeleaf:
    cache: false
  task:
    execution:
      pool:
        core-size: 20
        max-size: 50
  session:
    store-type: redis
  rabbitmq:
    virtual-host: /
    host: 192.168.127.138
management:
  endpoints:
    web:
      exposure:
        # * 在yaml中属于关键字
        include: "*"

logging:
  level:
    #远程调用打印日志
    org.springframework.cloud.openFeign: debug
    #链路追踪打印日志
    org.springframework.cloud.sleuth: debug
