server:
  port: 8000

spring:
  datasource:
    username: root
    password: lcl19960822
    url: jdbc:mysql://192.168.127.135:3308/gulimall_oms
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/order/*.xml
  #  主键自增
  global-config:
    db-config:
      id-type: auto
