spring:
  zipkin:
    base-url: http://192.168.127.138:9411/
    #zipkin关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #采样器，默认为0.1，即采样10%；
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
#        路由先适配更加精确的断言
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: oss_policy
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_level
          uri: lb://gulimall-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: repository_service
          uri: lb://gulimall-repository
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_service
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: admin_route
#          负载均衡发送到[服务名]所对应的地址
          uri: lb://renren-fast
          predicates:
#           前端项目发送的请求均带有api前缀，发送到网关
#           前端发送的请求：http://localhost:88/api/captcha.jpg => http://renren-fast:8080/api/captcha.jpg
#           然后验证码的请求地址为：http://renren-fast:8080/renren-fast/captcha.jpg，因此访问还是存在问题？
#           使用网关带的路径重写功能；rewrite path
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: gulimall-search-route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        - id: gulimall-auth-route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com

        - id: gulimall-cart-route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: gulimall-order-route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        - id: gulimall-user-route
          uri: lb://gulimall-user
          predicates:
            - Host=user.gulimall.com

        - id: gulimall-seckill-route
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com

        - id: gulimall-host-route
          uri: lb://gulimall-product
          predicates:
            - Host=**.gulimall.com,item.gulimall.com
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    #远程调用打印日志
    org.springframework.cloud.openFeign: debug
    #链路追踪打印日志
    org.springframework.cloud.sleuth: debug
